# Generated by Django 4.2.6 on 2024-03-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0006_alter_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.product",
            ),
        ),
    ]
